name: Build and deploy front
on: 
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: front-mini   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'front-mini'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '18.x'       
jobs:
    
    Build: 
        runs-on: ubuntu-latest
        #needs: Test
        name: Build and Deploy

        steps:
        - uses: actions/checkout@main
        - name: Use Node.js ${{ env.NODE_VERSION }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ env.NODE_VERSION }}
        - name: Cache dependencies
          uses: actions/cache@v2
          with:
            path: ~/.npm
            key: npm-${{ hashFiles('package-lock.json') }}
            restore-keys: npm-
    
        - name: Install dependencies
          run: npm ci --ignore-scripts
          working-directory: ./front

        # - name: Install dependencies
        #   run: npm install
        #   working-directory: ./front-mini

        - name: Build app
          run: npm run build --prefix front/
  
        - name: Zip build folder
          run: |
            cd front
            zip -r ./build.zip .
  
        - name: Create build artifact
          uses: actions/upload-artifact@v2
          with:
            name: build
            path: front/build.zip

        - name: Azure Login
          uses: azure/login@v1
          with: 
            creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'  

        - name: 'Deploy to Azure WebApp'
          uses: azure/webapps-deploy@v1
          with: 
            app-name: '${{vars.PREFIX}}-${{vars.APPLICATION }}-${{vars.ENVIRONMENT}}-front'
            package: front/build.zip

        - name: Remove artifact
          run: rm -rf front/build

            
