name: Deploy frontend
on: 
  push:

jobs:
    # Test: 
    #     runs-on: ubuntu-latest
    #     steps: 
    #         - name: Checkout
    #           uses: actions/checkout@v3
              
    #         - name: Install depenedencies
    #           run: npm ci 
    #           working-directory: ./front-mini

    #         # - name: Lint code
    #         #   run: npm run lint
    #         #   working-directory: ./front-mini

    #         - name: Test code
    #           run: npm run test
    #           working-directory: ./front-mini
    
    Build: 
        runs-on: ubuntu-latest
        #needs: Test
        steps: 
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Install depenedencies
              run: npm ci 
              working-directory: ./front-mini

            - name: Build frontend
              run: npm run build
              working-directory: ./front-mini
            
    Deploy: 
        runs-on: ubuntu-latest
        needs: Build
        steps: 
            - name: Deploy
              run: echo "deploying..." 
              working-directory: ./front-mini