name: Deploy frontend
on: 
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: front-mini   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'front-mini'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '18.x'       
jobs:
    # Test: 
    #     runs-on: ubuntu-latest
    #     steps: 
    #         - name: Checkout
    #           uses: actions/checkout@v3
              
    #         - name: Install depenedencies
    #           run: npm ci 
    #           working-directory: ./front-mini

    #         # - name: Lint code
    #         #   run: npm run lint
    #         #   working-directory: ./front-mini

    #         - name: Test code
    #           run: npm run test
    #           working-directory: ./front-mini
    
    Build: 
        runs-on: ubuntu-latest
        #needs: Test
        name: Build and Deploy

        steps:
        - uses: actions/checkout@main
        - name: Use Node.js ${{ env.NODE_VERSION }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ env.NODE_VERSION }}
        - name: npm install, build, and test
          run: |
            # Build and test the project, then
            # deploy to Azure Web App.
            npm install
            npm run build --if-present         
          working-directory: ./front-mini
        - name: ls 
          run: |
            ls -a       
          working-directory: ./front-mini

              # Zip artifacts to speed things up
        - name: Zip artifact for deployment
          run: zip release.zip ./* -r
          working-directory: ./front-mini
        - name: ls 2
          run: |
            ls -a       
          working-directory: ./front-mini
        - name: Upload artifact for deployment job
          uses: actions/upload-artifact@v2
          with:
            name: node-app
            path: release.zip
          
#npm run build --if-present
#npm run test --if-present
        - name: Azure Login
          uses: azure/login@v1
          with: 
            creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'  
        - name: Download artifact from build job
          uses: actions/download-artifact@v2
          with:
            name: node-app
        - name: unzip artifact for deployment
          run: unzip release.zip
        - name: 'Deploy to Azure WebApp'
          uses: azure/webapps-deploy@v1
          with: 
            app-name: '${{vars.PREFIX}}-${{vars.APPLICATION }}-${{vars.ENVIRONMENT}}-front'
            package: .

            