name: Deploy frontend
on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
    # Test: 
    #     runs-on: ubuntu-latest
    #     steps: 
    #         - name: Checkout
    #           uses: actions/checkout@v3
              
    #         - name: Install depenedencies
    #           run: npm ci 
    #           working-directory: ./front-mini

    #         # - name: Lint code
    #         #   run: npm run lint
    #         #   working-directory: ./front-mini

    #         - name: Test code
    #           run: npm run test
    #           working-directory: ./front-mini
    
    Build: 
        runs-on: ubuntu-latest
        #needs: Test
        steps: 
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Install depenedencies
              run: npm ci 
              working-directory: ./front-mini

            - name: Build frontend
              run: npm run build
              working-directory: ./front-mini

            - name: Azure Login
              uses: azure/login@v1
              with: 
                creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'
         
            - uses: ls -a
            
            - uses: azure/webapps-deploy@v1
              with:
                app-name: '${{vars.PREFIX}}-${{vars.APPLICATION }}-${{vars.ENVIRONMENT}}-front'
                package: front-mini
            