name: Build and deploy front to storage account
on: 
  push:
    branches:
      - master
    paths:
    - "front/**"
    - ".github/workflows/storage-front_ci.yaml"
  workflow_dispatch:

jobs:
  Build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Cache dependencies
          uses: actions/cache@v3
          with:
            path: ~/.npm
            key: node-modules-${{ hashFiles('**/package-lock.json') }}

        - name: Install dependencies
          run: npm ci
          working-directory: ./front

        - name: Build frontend
          run: CI=false REACT_APP_API_URL = ${{vars.PREFIX}}-${{vars.APPLICATION }}-${{vars.ENVIRONMENT}}-api.azurewebsites.net npm run build
          working-directory: ./front
  
        - name: Upload artifact
          uses: actions/upload-artifact@v3
          with:
            name: frontend
            path: ./front/build
    
  Deploy:
      runs-on: ubuntu-latest
      needs:
        - Build
      steps:
        - name: Get build artifact
          uses: actions/download-artifact@v3
          with:
            name: frontend

        - name: Login to Azure CLI
          uses: azure/login@v1
          with:
            creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'

        - name: Upload files to Storage Account
          run: |
              az storage blob upload-batch \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
              --overwrite \
              --destination \$web --source .
          